/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hr_pmf_project_rating_Event */

#ifndef _Included_hr_pmf_project_rating_Event
#define _Included_hr_pmf_project_rating_Event
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hr_pmf_project_rating_Event
 * Method:    firstSolveZero
 * Signature: (ILjava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;D)D
 */
JNIEXPORT jdouble JNICALL Java_hr_pmf_project_rating_Event_firstSolveZero
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jdouble);

/*
 * Class:     hr_pmf_project_rating_Event
 * Method:    secondSolveZero
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;DD)D
 */
JNIEXPORT jdouble JNICALL Java_hr_pmf_project_rating_Event_secondSolveZero
  (JNIEnv *, jobject, jobject, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
